version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    network_mode: "host"

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    network_mode: "host"